# The address for your CloudForms installation
cloudforms_api_url: "https://labs.opentlc.com"

# Packages needed for Bastion
bastion_packages: [ screen ]

# OpenShift 4 Pull Secret File
openshift_pull_secret_file: "/Users/mauricio/Documents/openshift-maltron-pull-secret.txt"

# AWS Information
aws_region: "us-east-2"
aws_client: { url: "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip", filename: "awscli-bundle.zip" }

# OpenShift Version 
openshift_version: "4.3.1"
openshift_install: { url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-install-linux-{{ openshift_version }}.tar.gz", filename: "openshift-install.tar.gz" }
openshift_client: { url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux-{{ openshift_version }}.tar.gz", filename: "openshift-client.tar.gz" }

# (Optional) A custom public key file with all your needed public keys
#            which it's going to be inserted into Bastion's authorized_key
personal_pub_file: "{{ ansible_env.HOME }}/.ssh/maltron.pub"

# (Optional) If you want to automatically open the browser
#            provide the location of your browser
google_chrome: "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome"
