- name: "{{ application }} >> Delete any existing directory: {{ directory }}"
  file: path={{ directory }} state=absent

- name: "{{ application }} >> Creating directory: {{ directory }}"
  file: path={{ directory }} state=directory 

- name: "{{ application }} >> Defining filename: {{ directory }}/{{ application }}.{{ extension }}"
  set_fact: filename="{{ directory }}/{{ application }}.{{ extension }}"

- name: "{{ application }} >> Downloading: {{ url }}"
  uri: url={{ url }} dest={{ filename }} headers={{ headers }} validate_certs=False

- name: "{{ application }} >> Unarchiving {{ filename }} into {{ directory }}"
  unarchive: src={{ filename }} dest={{ directory }}

- name: "{{ application }} >> Looking for the first directory created"
  find: path={{ directory }} file_type=directory
  register: found_directory

- name: "{{ application }} >> Moving directory name into {{ application }}"
  command: mv {{ found_directory.files[0].path }} {{ directory }}/{{ application }}
  when: found_directory.matched > 0

- name: "{{ application }} >> Deleting file: {{ filename }}"
  file: path={{ filename }} state=absent

- name: "{{ application }} >> Adding an Environment variable"
  lineinfile: path={{ ansible_env.HOME }}/.bashrc insertafter=EOF line="export {{ env_variable }}"
  when: env_variable is defined and env_variable is not none

- name: "{{ application }} >> Adding executable into the PATH"
  lineinfile: path={{ ansible_env.HOME }}/.bashrc insertafter=EOF line="export PATH=${PATH}:{{ executable_directory }}"
  when: executable_directory is defined and executable_directory is not none
  

