#!/usr/bin/env ansible-playbook
---
- name: Installing all the necessary tooling 
  hosts: localhost
  gather_facts: True
  vars:
     client_directory: "{{ ansible_env.HOME }}/k8s/client"
     runtime_directory: "{{ ansible_env.HOME }}/k8s/runtime"
     tooling_directory: "{{ ansible_env.HOME }}/k8s/tool"
  vars_files: 
     - tooling.config
  roles:
    - role: variables
      env: "JAVA_HOME=/root/test_java/java"
      executable_directory: "${JAVA_HOME}/bin:{{ client_directory }}/istio:{{ client_directory }}/knative:{{ client_directory }}/odo"
      tags: [ java, istio, environment, knative, odo ]
    - role: install_docker_ce
      tags: [ docker ]
    - role: install_rpm
      rpm_url: "{{ appsody_url }}" 
      tags: [ appsody ]
    - role: install_java
      application: "java"
      directory: "/root/test_java"
      url: "{{ java8_url }}" 
      tags: [ java ]
    # - role: install
    #   application: "maven"
    #   directory: "{{ tooling_directory }}/apache"
    #   url: "{{ maven_url }}" 
    #   env_variable: "MAVEN_HOME={{ tooling_directory }}/apache/{{ application }}"
    #   executable_directory: "${MAVEN_HOME}/bin"
    #   tags: [ maven ]
    - role: install_targz_single
      application: "istio"
      directory: "{{ client_directory }}/istio"
      url: "{{ istio_url }}" 
      tags: [ istio ]
    - role: install_straight
      application: "knative"
      application_name: "kn"
      directory: "{{ client_directory }}/knative"
      url: "{{ knative_url }}" 
      tags: [ knative ]
    - role: install_straight
      application: "odo"
      application_name: "odo"
      directory: "{{ client_directory }}/odo"
      url: "{{ odo_url }}" 
      tags: [ odo ]
    # - role: install
    #   application: "odo"
    #   application_name: "odo"
    #   directory: "{{ client_directory }}/{{ application }}"
    #   url: "{{ odo_url }}" 
    #   extension: ""
    #   executable_directory: "{{ directory }}"
    #   tags: [ odo ]
    - role: install
      application: "golang"
      directory: "{{ runtime_directory }}"
      url: "{{ go_url }}"
      executable_directory: "{{ runtime_directory }}/{{ application }}/bin"
      tags: [ golang ]
    - role: git2
      tags: [ git2 ]

- name: Adding Lance's Repository Boson
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
     - name: Add the boson stack repository
       command: appsody repo add boson https://github.com/openshift-cloud-functions/stacks/releases/latest/download/boson-index.yaml
       tags: [ lance ]
    
