#!/usr/bin/env ansible-playbook
---
- name: Installing all the necessary tooling 
  hosts: localhost
  gather_facts: True
  vars:
     client_directory: "{{ ansible_env.HOME }}/k8s/client"
     runtime_directory: "{{ ansible_env.HOME }}/k8s/runtime"
     tooling_directory: "{{ ansible_env.HOME }}/k8s/tool"
  vars_files: 
     - tooling.config
  roles:
    - role: install
      application: "java"
      directory: "{{ runtime_directory }}"
      url: "{{ java8_url }}" 
      headers: {"Cookie":"oraclelicense=accept-securebackup-cookie"}
      env_variable: "JAVA_HOME={{ directory }}/{{ application }}"
      executable_directory: "${JAVA_HOME}/bin"
      tags: [ java ]
    - role: install
      application: "maven"
      directory: "{{ tooling_directory }}/apache"
      url: "{{ maven_url }}" 
      env_variable: "MAVEN_HOME={{ tooling_directory }}/apache/{{ application }}"
      executable_directory: "${MAVEN_HOME}/bin"
      tags: [ maven ]
    - role: install
      application: "istio"
      application_name: "istioctl"
      directory: "{{ client_directory }}/{{ application }}"
      url: "{{ istio_url }}" 
      executable_directory: "{{ directory }}"
      tags: [ istio ]
    - role: install
      application: "knative"
      application_name: "kn"
      directory: "{{ client_directory }}/{{ application }}"
      url: "{{ knative_url }}" 
      extension: ""
      executable_directory: "{{ directory }}"
      tags: [ knative ]
    - role: install
      application: "odo"
      application_name: "odo"
      directory: "{{ client_directory }}/{{ application }}"
      url: "{{ odo_url }}" 
      extension: ""
      executable_directory: "{{ directory }}"
      tags: [ odo ]
    - role: install
      application: "appsody"
      application_name: "appsody"
      directory: "{{ client_directory }}/{{ application }}"
      url: "{{ appsody_url }}" 
      executable_directory: "{{ directory }}"
      tags: [ appsody ]
    - role: install
      application: "golang"
      directory: "{{ runtime_directory }}"
      url: "{{ go_url }}"
      executable_directory: "{{ runtime_directory }}/{{ application }}/bin"
      tags: [ golang ]
    - role: git2
      tags: [ git2 ]
    