#!/usr/bin/env ansible-playbook
---
- name: Installing all the necessary tooling 
  hosts: localhost
  gather_facts: True
  vars:
     client_directory: "{{ ansible_env.HOME }}/k8s/client"
     runtime_directory: "{{ ansible_env.HOME }}/k8s/runtime"
     tooling_directory: "{{ ansible_env.HOME }}/k8s/tool"
  vars_files: 
     - tooling.config
  roles:
    - role: variables
      env: "JAVA_HOME={{ runtime_directory }}/java MAVEN_HOME={{ client_directory }}/maven GOROOT={{ runtime_directory }}/go GOPATH={{ ansible_env.HOME }}/go_workspace"
      executable_directory: "${JAVA_HOME}/bin:${MAVEN_HOME}/bin:{{ client_directory }}/istio:{{ client_directory }}/knative:{{ client_directory }}/odo:{{ client_directory }}/etcd:{{ runtime_directory }}/go/bin"
      tags: [ java, istio, environment, knative, odo, etcd, maven, go ]
    - role: install_docker_ce
      tags: [ docker ]
    - role: install_rpm
      rpm_url: "{{ appsody_url }}" 
      tags: [ appsody ]
    - role: install_targz_single
      application: "istio"
      directory: "{{ client_directory }}/istio"
      url: "{{ istio_url }}" 
      tags: [ istio ]
    - role: install_targz
      application: "etcd"
      directory: "{{ client_directory }}"
      url: "{{ etcd_url }}" 
      tags: [ etcd ]
    - role: install_straight
      application: "knative"
      application_name: "kn"
      directory: "{{ client_directory }}/knative"
      url: "{{ knative_url }}" 
      tags: [ knative ]
    - role: install_straight
      application: "odo"
      application_name: "odo"
      directory: "{{ client_directory }}/odo"
      url: "{{ odo_url }}" 
      tags: [ odo ]
    - role: install_targz
      application: "go"
      directory: "{{ runtime_directory }}"
      url: "{{ go_url }}"
      skip_moving: True
      tags: [ go ]
    - role: install_targz
      application: "java"
      headers: {"Cookie":"oraclelicense=accept-securebackup-cookie"}
      directory: "{{ runtime_directory }}"
      url: "{{ java8_url }}"
      tags: [ java ]
    - role: install_targz
      application: "maven"
      directory: "{{ client_directory }}"
      url: "{{ maven_url }}"
      tags: [ maven ]
    - role: git2
      tags: [ git2 ]

- name: Additional configuration go Go Language
  hosts: localhost
  connection: local
  gather_facts: True
  tasks:
     - name: Creating Workspace directory for Go Language
       file: path={{ ansible_env.HOME }}/go_workspace state=directory
       tags: [ go ]

- name: Adding Lance's Repository Boson
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
     - name: Add the boson stack repository
       command: appsody repo add boson https://github.com/openshift-cloud-functions/stacks/releases/latest/download/boson-index.yaml
       tags: [ lance ]
    
